ticket_management/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ticket.views import  *
from django.contrib.auth import views as auth_views
from ticket.csv_manipulation import upload_csv
from ticket.pdf_generation import *
from ticket.voucher_views import *
from ticket.parse_ticket_pdf import *
from ticket.bank_views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticket/password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),  name="reset_password"),
    path('ticket/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"
    ),
    path('ticket/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('ticket/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
    path("__reload__/", include("django_browser_reload.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('tickets/', index, name='index'),
    path('get_ticket/', get_ticket, name='get_ticket'),
    path('ticket/login/', login_user, name='login'),    
    path('', login_user, name='login'),
    path('logout_user', logout_user, name='logout_user'),
    path('ticket/', include('django.contrib.auth.urls')),
    path('tickets/csv', generateCSV, name='get_csv'),
    path('tickets/create/', ticket_create, name='ticket_create'),
    path('tickets/urgent/', urgent_tickets, name='urgent_tickets'),
    path('tickets/<int:pk>/update/', ticket_update, name='ticket_update'),
    path('delete/<str:model_name>/<int:pk>/delete/', delete_record, name='delete_record'),
    path('tickets/search/', search, name='search'),
    path('ledgers/', ledger_list, name='ledger_list'),
    path('ledgers/create/', ledger_create, name='ledger_create'),
    path('ledgers/<int:pk>/update/', ledger_update, name='ledger_update'),
    path('suppliers/', supplier_list, name='supplier_list'),
    path('suppliers/create/', supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/update/', supplier_update, name='supplier_update'),
    path('customers/create/', customer_create, name='customer_create'),
    path('customers/<int:pk>/update/', customer_update, name='customer_update'),
    path('customers/', customer_list, name='customer_list'),
    path('ledgers/<str:pk>/<str:model_name>', supplier_ledger, name='supplier_ledger'),
    path('generate_pdf', generatePDF, name='generate_pdf'),
    path('tickets/upload/', upload_csv, name='upload_file'),
    path('visas', visa_list, name='visa_list'),
    path('visa/create', visa_create, name='visa_create'),
    path('visa/update/<int:pk>', visa_update, name='visa_update'),
    path('riyalprice_create/create', riyalprice_create, name='riyalprice_create'),
    path('profit/', profit, name='profit'),
    path('hotel_list/', hotel_list, name='hotel_list'),
    path('update_hotel/<int:pk>/', update_hotel, name='update_hotel'),
    path('add_hotel/', add_hotel, name='add_hotel'),
    path('parse_file/', parse_file, name='parse_file'),
    path('parse_pdf/', parse_pdf, name='parse_pdf'),
    path('ajax/load-hotels/', load_hotels, name='ajax_load_hotels'),
    path('ajax/load-rooms/', load_rooms, name='ajax_load_rooms'),
    path('ajax/get_visas/', get_visas, name='ajax_get_visas'),
    path('create_voucher/', create_voucher, name='create_voucher'),
    path('update_voucher/<int:pk>', update_voucher, name='update_voucher'),
    path('vouchers/', vouchers, name='vouchers'),
    path('banks/', banks, name='banks'),
    path('bank_create/', bank_create, name='bank_create'),
    path('bank_update/', bank_update, name='bank_update'),
    
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ticket/models.py
from django.db import models, transaction
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

    
class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    opening_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.name}"

class Supplier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    opening_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    def __str__(self):
        return f"{self.name}"
class Issued(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issued_by=models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return f"{self.issued_by}"

class Ticket(models.Model):
    TICKET_TYPES = [
        ('IS', 'Issues'),
        ('RF', 'Refund'),
        ('RI', 'ReIssue'),
        ('VO', 'Void'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    pnr = models.CharField(max_length=100, blank=False, null=False)
    sector = models.CharField(max_length=255, blank= True, null=True)
    passenger = models.CharField(max_length=255, blank= True, null=True)
    travel_date = models.DateTimeField(blank=True, null=True)
    return_date = models.DateTimeField(blank=True, null=True)
    airline = models.CharField(max_length=255, blank= True, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, blank=False, null=False, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=False, null=False, db_index=True)
    sale = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    purchase = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    ticket_type = models.CharField(max_length=2,choices=TICKET_TYPES,default='Issues', blank=False, null=False)
    narration= models.TextField(blank=True, null=True, default="")
    excel_id= models.PositiveIntegerField(null=True, blank=True, default=0)
    issued_by=models.ForeignKey(Issued, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return (
        f"Ticket with PNR: {self.pnr}<br>"
        f"Travel Date: {self.travel_date}<br>"
        f"Supplier: {self.supplier}<br>"
        f"Customer: {self.customer}<br>"
        f"Passenger: {self.passenger}"
        )

class Bank(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)

class Ledger(models.Model):
    Status_Choices = [
        (0, 'Pending'),
        (1, 'Approved'),
        (2, 'Rejected'),
    ]
    TRANSACTION_TYPE=[
        (0, 'Debit'),
        (1, 'Credit'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    payment = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    payment_date = models.DateTimeField(default=timezone.now)
    description= models.TextField( blank=True, null=True, default="")
    status = models.SmallIntegerField(choices=Status_Choices,default=1, blank=True, null=True)
    transaction_type = models.SmallIntegerField(choices=TRANSACTION_TYPE, blank=True,null=True)
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name='ledgers', null=True, blank=True, db_index=True)
    
    @transaction.atomic
    def save(self, *args, **kwargs):
        if self.bank:
            if self.transaction_type == self.DEBIT:
                if self.bank.balance < self.payment:
                    raise ValidationError("Insufficient balance in bank.")
                else:
                    self.bank.balance -= self.payment
            elif self.transaction_type == self.CREDIT:
                self.bank.balance += self.payment
            self.bank.save()
        super().save(*args, **kwargs)
def __str__(self):
    return f"By {self.user}  {self.payment} to {self.supplier} on {self.payment_date}"

class RiyalPrice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True)
    
    def __str__(self):
        return f"Price {self.price}"
class Visa(models.Model):
    VISA_TYPE = [
        ('DV', 'Dubai Visit'),
        ('SV', 'Saudia Visit'),
        ('DW', 'Dubai Work'),
        ('SW', 'Saudia Work'),
        ('UV', 'Umrah Visa' ), 
        ('HV', 'Hajj Visa' ), 
    ]
    DURATION_TYPE = [
        ('36', '36 Hours'),
        ('96', '96 Hours'),
        ('1m', '1 Month'),
        ('2m', '2 Months'),
        ('3m', '3 Months'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    riyal_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    sale = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    sale_pkr = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    purchase = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    purchase_pkr = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    pass_name= models.CharField(max_length=255, blank=True, null= True)
    pass_num= models.CharField(max_length=10, blank=True, null= True, db_index=True)

    visa_type = models.CharField(max_length = 2, choices=VISA_TYPE, blank= False, null= False)
    duration = models.CharField(max_length=2, choices=DURATION_TYPE, blank = False, null = False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.pass_name} / {self.pass_num}"
class Hotel(models.Model):
    CITY_CHOICES = [
        (0, 'Madinah'),
        (1, 'Makkah'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel_name = models.CharField(max_length=255, blank=True, null=True)
    area= models.CharField(max_length=255, blank=True, null=True)
    distance = models.PositiveIntegerField()
    city = models.SmallIntegerField( choices=CITY_CHOICES, blank=True, null=True)
    active = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.get_city_display()} {self.hotel_name} {self.area} {self.distance}m  "
class RoomRate(models.Model):
    ROOM_CATEGORY = [
        (0, 'Private'),
        (1, 'Sharing'),
        (2, 'Quadripple'),
        (3, 'Tripple'),
        (4, 'Double'),
    ]
    room_type = models.SmallIntegerField( choices=ROOM_CATEGORY, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel= models.ForeignKey(Hotel, on_delete=models.CASCADE)
    date_from = models.DateField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    riyal_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    riyal_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    pkr_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"Price for {self.get_room_type_display()} on {self.date_from} to {self.date_to} is {self.pkr_price} with {self.riyal_rate}"        
class Trip(models.Model):
    flight= models.CharField(max_length=10)
    sector= models.CharField(max_length=50)
    departure = models.DateField(blank=True, null=True)
    arrival = models.DateField(blank=True, null=True)
    
class HotelBooking(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room = models.ForeignKey(RoomRate, on_delete=models.CASCADE)
    voucher = models.ForeignKey('Voucher', on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()    
    nights = models.PositiveIntegerField()
class Voucher(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotels = models.ManyToManyField(Hotel, through=HotelBooking)
    visas = models.ManyToManyField(Visa, db_index=True)
    trip = models.ManyToManyField(Trip)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    transport = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        # Delete associated trips
        self.trip.all().delete()
        super().delete(*args, **kwargs)

ticket/templates/Visa/riyal_form.html
{% extends 'base.html' %}


{% block content %}

{% block page_title %}
{% if form.instance.id %} Update Riyal {% else %} Create Riyal {% endif %}
{% endblock %}
<div class="container mx-auto flex justify-center items-center py-6">

<div class="h-auto  mt-10  w-auto bg-teal-200 p-10 rounded-md bg-clip-padding backdrop-filter backdrop-blur-sm bg-opacity-40 border border-gray-100">

<div class="mx-auto max-w-2xl text-center">
    <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{% if form.instance.id %} Update riyal {% else %} Create riyal {% endif %}</h1>
  </div>
<form  id="riyal-form" method="POST" enctype="multipart/form-data" class="mx-auto mt-16  sm:mt-20">

    {% csrf_token %}
    <input type="hidden" id="user" name="user" value="{{ request.user.id }}">
    <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-x-8 gap-y-6 sm:grid-cols-2">

    
      <!-- riyal Field-->
      <div class= 'col-span-2 md:col-span-1 lg:col-span-4'>
        <label for="price" class="block text-sm font-semibold leading-6 text-gray-900">riyal Price</label>
        <div class="mt-2.5">
          <input type="number" step="0.01" name="price" required id="price" autocomplete="off" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" 
          value="{% if form.instance.price %}{{ form.instance.price }}{% endif %}">
        </div>
      </div>

        <!-- CREATED AT Field -->
      <div class= 'col-span-2 md:col-span-1 lg:col-span-4'>
        <label for="created_at" class="block text-sm font-semibold leading-6 text-gray-900">Created At</label>
        <div class="mt-2.5">
          <input type="datetime-local" name="created_at" id="created_at" autocomplete="off" class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" value="{{ form.instance.created_at|date:'Y-m-d\TH:i' }}">
        </div>
      </div>
      <div class="col-span-2 lg:col-span-4 flex justify-center mt-6">
        <div class="flex items-center space-x-4">
          <!-- Update or Save Ticket button -->
          <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">
            {% if form.instance.id %} Update Riyal {% else %} Save Riyal {% endif %}
          </button>
        </div>
      </div>
    </div>
  </div>
</form>

</div>
</div>

{% endblock %}

ticket/templates/Visa/visa_list.html
{% extends 'base.html' %}

{% block title %}Visa{% endblock %}

{% block content %}

<div class="mx-auto max-w-2xl text-center">
  <h5 class="text-xl font-bold tracking-tight text-gray-900 sm:text-2xl">Today's Riyal Price: {{price}}</h5>
</div>

<div class="mt-8 mx-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Date</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Pass Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Pass Num</th>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Supplier</th>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"> Customer </th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Purchase</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Sale</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">PKR Price</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Visa Type</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Duration</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6"></th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              {% for visa in visas %}
                <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ visa.created_at|date:"d-M" }}</td>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ visa.pass_name }} </td>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ visa.pass_num }} </td>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ visa.supplier.name }} </td>
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{visa.customer.name}} </td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ visa.purchase }} / {{visa.purchase_pkr}}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ visa.sale }} / {{visa.sale_pkr}}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"> {{ visa.get_visa_type_display }}</td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"> {{ visa.get_duration_display }}</td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                    <a href="{% url 'visa_update' pk=visa.pk %}" class="text-indigo-600 hover:text-indigo-900">Edit<span class="sr-only">, </span></a>
                    <a href="#" id="visa-del" data-tid="{{visa.pk}}" data-model="visa"  class="text-indigo-600 hover:text-indigo-900">Delete<span class="sr-only">, </span></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  
{% endblock%}