ticket_management/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from ticket.views import  *
from django.contrib.auth import views as auth_views
from ticket.csv_manipulation import upload_csv
from ticket.pdf_generation import *
from ticket.voucher_views import *
from ticket.parse_ticket_pdf import *
from ticket.bank_views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticket/password_reset/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),  name="reset_password"),
    path('ticket/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"
    ),
    path('ticket/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), name="password_reset_confirm"),
    path('ticket/reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
    path("__reload__/", include("django_browser_reload.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('tickets/', index, name='index'),
    path('get_ticket/', get_ticket, name='get_ticket'),
    path('ticket/login/', login_user, name='login'),    
    path('', login_user, name='login'),
    path('logout_user', logout_user, name='logout_user'),
    path('ticket/', include('django.contrib.auth.urls')),
    path('tickets/csv', generateCSV, name='get_csv'),
    path('tickets/create/', ticket_create, name='ticket_create'),
    path('tickets/urgent/', urgent_tickets, name='urgent_tickets'),
    path('tickets/<int:pk>/update/', ticket_update, name='ticket_update'),
    path('delete/<str:model_name>/<int:pk>/delete/', delete_record, name='delete_record'),
    path('tickets/search/', search, name='search'),
    path('ledgers/', ledger_list, name='ledger_list'),
    path('ledgers/create/', ledger_create, name='ledger_create'),
    path('ledgers/<int:pk>/update/', ledger_update, name='ledger_update'),
    path('suppliers/', supplier_list, name='supplier_list'),
    path('suppliers/create/', supplier_create, name='supplier_create'),
    path('suppliers/<int:pk>/update/', supplier_update, name='supplier_update'),
    path('customers/create/', customer_create, name='customer_create'),
    path('customers/<int:pk>/update/', customer_update, name='customer_update'),
    path('customers/', customer_list, name='customer_list'),
    path('ledgers/<str:pk>/<str:model_name>', supplier_ledger, name='supplier_ledger'),
    path('generate_pdf', generatePDF, name='generate_pdf'),
    path('tickets/upload/', upload_csv, name='upload_file'),
    path('visas', visa_list, name='visa_list'),
    path('visa/create', visa_create, name='visa_create'),
    path('visa/update/<int:pk>', visa_update, name='visa_update'),
    path('riyalprice_create/create', riyalprice_create, name='riyalprice_create'),
    path('profit/', profit, name='profit'),
    path('hotel_list/', hotel_list, name='hotel_list'),
    path('update_hotel/<int:pk>/', update_hotel, name='update_hotel'),
    path('add_hotel/', add_hotel, name='add_hotel'),
    path('parse_file/', parse_file, name='parse_file'),
    path('parse_pdf/', parse_pdf, name='parse_pdf'),
    path('ajax/load-hotels/', load_hotels, name='ajax_load_hotels'),
    path('ajax/load-rooms/', load_rooms, name='ajax_load_rooms'),
    path('ajax/get_visas/', get_visas, name='ajax_get_visas'),
    path('create_voucher/', create_voucher, name='create_voucher'),
    path('update_voucher/<int:pk>', update_voucher, name='update_voucher'),
    path('vouchers/', vouchers, name='vouchers'),
    path('banks/', banks, name='banks'),
    path('bank_create/', bank_create, name='bank_create'),
    path('bank_update/', bank_update, name='bank_update'),
    
    
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ticket/models.py
from django.db import models, transaction
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

    
class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    opening_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"{self.name}"

class Supplier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    opening_balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    def __str__(self):
        return f"{self.name}"
class Issued(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issued_by=models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return f"{self.issued_by}"

class Ticket(models.Model):
    TICKET_TYPES = [
        ('IS', 'Issues'),
        ('RF', 'Refund'),
        ('RI', 'ReIssue'),
        ('VO', 'Void'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    pnr = models.CharField(max_length=100, blank=False, null=False)
    sector = models.CharField(max_length=255, blank= True, null=True)
    passenger = models.CharField(max_length=255, blank= True, null=True)
    travel_date = models.DateTimeField(blank=True, null=True)
    return_date = models.DateTimeField(blank=True, null=True)
    airline = models.CharField(max_length=255, blank= True, null=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, blank=False, null=False, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=False, null=False, db_index=True)
    sale = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    purchase = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    ticket_type = models.CharField(max_length=2,choices=TICKET_TYPES,default='Issues', blank=False, null=False)
    narration= models.TextField(blank=True, null=True, default="")
    excel_id= models.PositiveIntegerField(null=True, blank=True, default=0)
    issued_by=models.ForeignKey(Issued, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return (
        f"Ticket with PNR: {self.pnr}<br>"
        f"Travel Date: {self.travel_date}<br>"
        f"Supplier: {self.supplier}<br>"
        f"Customer: {self.customer}<br>"
        f"Passenger: {self.passenger}"
        )

class Bank(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0.00)

class Ledger(models.Model):
    Status_Choices = [
        (0, 'Pending'),
        (1, 'Approved'),
        (2, 'Rejected'),
    ]
    TRANSACTION_TYPE=[
        (0, 'Debit'),
        (1, 'Credit'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    payment = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    payment_date = models.DateTimeField(default=timezone.now)
    description= models.TextField( blank=True, null=True, default="")
    status = models.SmallIntegerField(choices=Status_Choices,default=1, blank=True, null=True)
    transaction_type = models.SmallIntegerField(choices=TRANSACTION_TYPE, blank=True,null=True)
    bank = models.ForeignKey(Bank, on_delete=models.CASCADE, related_name='ledgers', null=True, blank=True, db_index=True)
    
    @transaction.atomic
    def save(self, *args, **kwargs):
        if self.bank:
            if self.transaction_type == self.DEBIT:
                if self.bank.balance < self.payment:
                    raise ValidationError("Insufficient balance in bank.")
                else:
                    self.bank.balance -= self.payment
            elif self.transaction_type == self.CREDIT:
                self.bank.balance += self.payment
            self.bank.save()
        super().save(*args, **kwargs)
def __str__(self):
    return f"By {self.user}  {self.payment} to {self.supplier} on {self.payment_date}"

class RiyalPrice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True)
    
    def __str__(self):
        return f"Price {self.price}"
class Visa(models.Model):
    VISA_TYPE = [
        ('DV', 'Dubai Visit'),
        ('SV', 'Saudia Visit'),
        ('DW', 'Dubai Work'),
        ('SW', 'Saudia Work'),
        ('UV', 'Umrah Visa' ), 
        ('HV', 'Hajj Visa' ), 
    ]
    DURATION_TYPE = [
        ('36', '36 Hours'),
        ('96', '96 Hours'),
        ('1m', '1 Month'),
        ('2m', '2 Months'),
        ('3m', '3 Months'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    riyal_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, blank=True, null=True, db_index=True)
    sale = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    sale_pkr = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    purchase = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    purchase_pkr = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    pass_name= models.CharField(max_length=255, blank=True, null= True)
    pass_num= models.CharField(max_length=10, blank=True, null= True, db_index=True)

    visa_type = models.CharField(max_length = 2, choices=VISA_TYPE, blank= False, null= False)
    duration = models.CharField(max_length=2, choices=DURATION_TYPE, blank = False, null = False)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.pass_name} / {self.pass_num}"
class Hotel(models.Model):
    CITY_CHOICES = [
        (0, 'Madinah'),
        (1, 'Makkah'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel_name = models.CharField(max_length=255, blank=True, null=True)
    area= models.CharField(max_length=255, blank=True, null=True)
    distance = models.PositiveIntegerField()
    city = models.SmallIntegerField( choices=CITY_CHOICES, blank=True, null=True)
    active = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.get_city_display()} {self.hotel_name} {self.area} {self.distance}m  "
class RoomRate(models.Model):
    ROOM_CATEGORY = [
        (0, 'Private'),
        (1, 'Sharing'),
        (2, 'Quadripple'),
        (3, 'Tripple'),
        (4, 'Double'),
    ]
    room_type = models.SmallIntegerField( choices=ROOM_CATEGORY, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel= models.ForeignKey(Hotel, on_delete=models.CASCADE)
    date_from = models.DateField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    riyal_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    riyal_rate = models.DecimalField(max_digits=10, decimal_places=2, default=0.00 )
    pkr_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f"Price for {self.get_room_type_display()} on {self.date_from} to {self.date_to} is {self.pkr_price} with {self.riyal_rate}"        
class Trip(models.Model):
    flight= models.CharField(max_length=10)
    sector= models.CharField(max_length=50)
    departure = models.DateField(blank=True, null=True)
    arrival = models.DateField(blank=True, null=True)
    
class HotelBooking(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room = models.ForeignKey(RoomRate, on_delete=models.CASCADE)
    voucher = models.ForeignKey('Voucher', on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()    
    nights = models.PositiveIntegerField()
class Voucher(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotels = models.ManyToManyField(Hotel, through=HotelBooking)
    visas = models.ManyToManyField(Visa, db_index=True)
    trip = models.ManyToManyField(Trip)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    transport = models.BooleanField(default=False)

    def delete(self, *args, **kwargs):
        # Delete associated trips
        self.trip.all().delete()
        super().delete(*args, **kwargs)

ticket/templates/partials/add_hotel.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content%}
<form method="post">
    <div class="container mx-10 my-10">
        <h5 class="text-lg font-bold tracking-tight flex justify-center mb-10 text-gray-900 sm:text-xl mt-5">Today's Riyal Price: {{riyal_rate}}</h5>
  <div class=" grid lg:grid-cols-6 md:grid-cols-6 gap-x-8 gap-y-6 sm:grid-cols-2">
    {% crispy form %}
       
</div>
    {{ formset.management_form }}
    <div class=" grid lg:grid-cols-6 md:grid-cols-6 gap-x-8 gap-y-6 sm:grid-cols-2">
    {% for form in formset %}
    {{ form.id }}    
    {{ form.user }}    
    {{ form.pkr_price.as_hidden }}    
    {{ form.riyal_rate.as_hidden }}    
    {{ form.room_type|as_crispy_field }}
    {{ form.riyal_price|as_crispy_field }}

    {% if forloop.counter0 == 4 %}
    {{ form.date_from|as_crispy_field }}
    {{ form.date_to|as_crispy_field }}
    {% endif %}
        
    {% endfor %}
</div>
    <div class="flex justify-center">
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-8">Save</button>
    </div>
</div>

</form>
{% endblock%}

ticket/templates/partials/bank_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content%}
<div class="h-full mt-10  w-full bg-teal-200 p-10 rounded-md bg-clip-padding backdrop-filter backdrop-blur-sm bg-opacity-40 border border-gray-100">

<form method="POST">
  <div class=" grid lg:grid-cols-6 md:grid-cols-6 gap-x-8 gap-y-6 sm:grid-cols-2">
    {% crispy form %}
    <button type="submit" id="bank_btn" class="bg-green-500 hover:bg-green-700 text-white font-bold px-4 py-2 rounded mt-8">
        Submit
        </button>
  </div>
</form>
<div>
{% endblock %}

ticket/templates/partials/form.html
{% extends "base.html" %}
{% block page_title %}
  {% if form.instance.id %}Update {{form.get_model_name}}  {%else%} Create {{form.get_model_name}}  {% endif %}
{% endblock %}

{% block content %}
  <div class="isolate bg-white add-bg ">
    {% if form.errors %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Oops! There was an error.</strong>
      <ul class="list-disc ml-5">
        {% for field in form %}
        {% for error in field.errors %}
        <li>{{ field.label }}: {{ error|escape }}</li>
        {% endfor %}
        {% endfor %}
      </ul>
    </div>
  {% endif %}
  <div class="flex items-center justify-center h-screen">
    <div class="h-auto max-w-xs bg-blue-300 p-10 rounded-md backdrop-filter backdrop-blur-sm bg-opacity-40 border border-gray-100">
    <div class="mx-auto max-w-2xl text-center">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">{% if form.instance.id %} Update {% else %} Create {% endif %}</h1>
    </div>
    <form method="POST"  enctype="multipart/form-data" class=" mx-auto mt-16 sm:mt-20">
      {% csrf_token %}
      
      <input type="hidden" name="user" value="{{ request.user.id }}">
      {% for field in form.visible_fields %}
      <div>
        <label for="{{ field.name }}" class="block text-sm font-semibold leading-6 text-gray-900">{{ field.label }}</label>
        <div class="mt-2.5">
              <input
                  type="{{ field.field.widget.input_type }}"
                  name="{{ field.name }}"
                  required
                  {% if field.id_for_label == "id_opening_balance" %}
                  id='currency'
                  {% else %}
                  id="{{ field.id_for_label }}"
                  {% endif %}
                  autocomplete="off"
                  class="block w-full rounded-md border-0 px-3.5 py-2 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  value="{{ field.value|default:'' }}">
          </div>
      </div>
      
      {% endfor %}
      <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-x-8 gap-y-6 sm:grid-cols-2">

        <div class="col-span-4 flex justify-center mt-6">
          <div class="flex items-center space-x-4">
            <!-- Update or Save Ticket button -->
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">
              {% if form.instance.id %} Update {% else %} Save  {% endif %}
            </button>
            <button type="submit" name="save_and_add_another" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">
              {% if form.instance.id %} Add Another {% else %}Add Another {% endif %}
            </button>


          </div>
        </div>
        
      </div> <!--Grid End-->
    </div>
      </div>
    </div>
      </form>
      </div>
  {% endblock %}
  

ticket/templates/partials/hotel_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content%}
<div class="h-full mt-10  w-full bg-teal-200 p-10 rounded-md bg-clip-padding backdrop-filter backdrop-blur-sm bg-opacity-40 border border-gray-100">

<form method="POST">
  <div class=" grid lg:grid-cols-6 md:grid-cols-6 gap-x-8 gap-y-6 sm:grid-cols-2">
    {% crispy form %}
  </div>
</form>
<div>
{% endblock %}

ticket/templates/partials/info_alert.html
{% block content %}

<div class="info-alert rounded-md bg-green-50 p-4 m-2 ">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-green-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <p class="text-sm font-medium text-green-800">{{ message }}</p>
    </div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button type="button"  id= "close-alert"class="inline-flex rounded-md bg-green-50 p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:ring-2 focus:ring-green-600 focus:ring-offset-2 focus:ring-offset-green-50">
          <span class="sr-only">Dismiss</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>

{% endblock%}

ticket/templates/partials/pagination.html
<div class="flex justify-center my-4">
    <ul class="flex list-none">
        {% if objects.has_previous %}
            <li class="mr-2">
                <a href="?page=1" class="text-blue-500 hover:text-blue-700">First</a>
            </li>
            <li class="mr-2">
                <a href="?page={{ objects.previous_page_number }}" class="text-blue-500 hover:text-blue-700">Previous</a>
            </li>
        {% endif %}
        <li class="mr-2">
         Page  {{ objects.number}} of {{ objects.paginator.num_pages}}
      </li>
        {% if objects.has_next %}
            <li class="mr-2">
                <a href="?page={{ objects.next_page_number }}" class="text-blue-500 hover:text-blue-700">Next</a>
            </li>
            <li class="mr-2">
                <a href="?page={{ objects.paginator.num_pages }}" class="text-blue-500 hover:text-blue-700">Last</a>
            </li>
        {% endif %}
    </ul>
</div>

ticket/templates/partials/roomrate_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content%}
<div class="h-full mt-10  w-full bg-teal-200 p-10 rounded-md bg-clip-padding backdrop-filter backdrop-blur-sm bg-opacity-40 border border-gray-100">

<form method="post">
  <div class=" grid lg:grid-cols-6 md:grid-cols-6 gap-x-8 gap-y-6 sm:grid-cols-2">
    {% crispy form %}
  </div>
</form>
<div>
  <script>
    $(document).ready(function () {

        $("#supplier_id").select2({
            placeholder: "Select a Supplier",
            allowClear: true,
            theme: "classic"
        });
    });
</script>

{% endblock %}

ticket/templates/partials/voucher.html
{% extends 'base.html' %}
{% block content %}
{% for voucher in vouchers %}

<div class="max-w-screen-xl my-5 mx-auto">
    <!-- Card container -->
    <div class="bg-white rounded-xl shadow-md overflow-hidden flex relative">
        <!-- Left section (20%) -->
        <!-- Icon -->
        <div class=" w-6 h-6 absolute top-0 right-0 m-2  inline-block text-center ">
            <div>
                <button type="button" id="voucher-btn-{{voucher.id}}" data-dropdown-toggle="voucher-menu-{{voucher.id}}" class="-m-2 p-2 rounded-full flex items-center text-gray-400 hover:text-gray-600 focus:outline-none">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>
                </button>
            </div>
        
            <!-- Dropdown panel, show/hide based on dropdown state. -->
            <div id="voucher-menu-{{voucher.id}}" class="origin-top-right absolute left-0 mt-2 w-15 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 hidden">
                <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="voucher-btn-{{voucher.id}}">
                    <a href="{% url 'update_voucher' pk=voucher.id %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">Edit</a>
                  <a href="#" id="voucher-del" data-tid="{{voucher.id}}" data-model="voucher"  class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900"> Del</a>
                </div>
            </div>
        </div>
                
        
        <div class="w-1/5 bg-gray-100 px-6">
            <h3 class="font-bold text-lg text-center mb-4">Visas</h3>
            <!-- Display associated visas -->
            <div class="flex flex-col items-center">
                {% for visa in voucher.visas.all %}

                <div class="mb-4 flex justify-between">
                    <div class="text-sm font-medium text-gray-800">{{ visa.pass_name }}</div>
                    <div class="text-sm text-gray-600">/ {{ visa.pass_num }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- Right section (80%) -->
        <div class="flex-grow bg-gray-200 px-6">
            <!-- Display associated hotels -->
            <div class="mb-8">
                <h3 class="font-bold text-lg text-center mb-4">Hotels</h3>
                {% for hotel_booking in voucher.hotelbooking_set.all %}
                <div class="mb-4">
                    <table class="table-auto border-collapse w-full">
                        <tbody>
                            <tr class="text-left">
                                <td class="w-1/6 text-sm font-semibold text-gray-700"><span class="font-bold">City:</span> {{ hotel_booking.hotel.get_city_display }}</td>
                                <td class="w-1/4 text-sm font-semibold text-gray-700"><span class="font-bold">Hotel:</span> {{ hotel_booking.hotel.hotel_name }}</td>
                                <td class="w-32 text-sm font-semibold text-gray-700"><span class="font-bold">Room:</span> {{ hotel_booking.room.get_room_type_display }}</td>
                                <td class="w-40 text-sm text-gray-600"><span class="font-bold">Check-in:</span> {{ hotel_booking.check_in }}</td>
                                <td class="w-40 text-sm text-gray-600"><span class="font-bold">Check-out:</span> {{ hotel_booking.check_out }}</td>
                                <td class="w-1/12  text-sm text-gray-600"><span class="font-bold">Nights:</span> {{ hotel_booking.nights }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                {% endfor %}
            </div>
            <h3 class="font-semibold text-sm text-center mb-4">
                Need Company Transport: 
                <span class="font-bold {% if voucher.transport %}text-green-500{% else %}text-red-500{% endif %}">
                    {{ voucher.transport }}
                </span>
            </h3>
            

            <!-- Display associated trips -->
            <div>
                <h3 class="font-bold text-lg text-center mb-4">Trips</h3>
                {% for trip in voucher.trip.all %}
                <div class="mb-4">
                    <table class="table-auto border-collapse w-full">
                        <tbody>
                            <tr class="text-left">
                                <td class="w-1/4 text-sm font-semibold text-gray-700"><span class="font-bold">Flight:</span> {{ trip.flight }}</td>
                                <td class="w-1/4 text-sm font-semibold text-gray-700"><span class="font-bold">Sector:</span> {{ trip.sector }}</td>
                                <td class="w-1/4 text-sm font-semibold text-gray-700"><span class="font-bold">Dep:</span> {{ trip.departure }}</td>
                                <td class="w-1/4 text-sm font-semibold text-gray-700"><span class="font-bold">Arr:</span> {{ trip.arrival }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}